[package]
name = "gander"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI client for SQL databases"
repository = "https://github.com/lewissteele/gander"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
